baseURL: "https://hgminh.dev/"
languageCode: "en-us"
title: "hgminh's blog"

theme: "mini"

paginate: 10

permalinks:
  posts: /posts/:title/

taxonomies:
  tag: tags

params:
  author: hgminh
  description: My Blog

  enableRSS: true
  enableComments: true
  enableGoogleAnalytics: false
  showToc: true
  showPowerBy: false
  math: true
  copyright: ''

  links:
    - name: Github
      path: https://github.com/hgminh95/blog
